server.port=9000

server.servlet.context-path=

springdoc.swagger-ui.path=/

# mongo db connection string
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/analytics_lab?authSource=admin

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
